# Generated by Django 4.2.5 on 2023-11-17 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ott', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UploadedContent',
            new_name='Ott',
        ),
    ]
