# Generated by Django 4.2.5 on 2023-12-12 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ott', '0003_ott_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ott',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
