# Generated by Django 4.2.5 on 2023-10-10 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('phone_number', models.CharField(max_length=15, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('referral_code', models.CharField(blank=True, max_length=10, null=True)),
                ('password', models.CharField(max_length=128)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('username_code', models.CharField(blank=True, max_length=15, null=True, unique=True)),
                ('status', models.IntegerField(default=1)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('slug', models.CharField(blank=True, max_length=15, null=True, unique=True)),
                ('blocked_users', models.ManyToManyField(blank=True, related_name='users_blocked_by', to='registration.user')),
            ],
        ),
    ]
