# Generated by Django 4.2.5 on 2023-10-10 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
