# Generated by Django 4.2.5 on 2023-10-18 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoupload', '0005_remove_video_is_share_point_is_share'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='point',
            name='is_share',
        ),
        migrations.AddField(
            model_name='video',
            name='is_share',
            field=models.BooleanField(default=False),
        ),
    ]
