# Generated by Django 4.2.5 on 2023-10-18 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoupload', '0007_remove_video_is_share_point_is_share'),
    ]

    operations = [
        migrations.AlterField(
            model_name='point',
            name='is_share',
            field=models.IntegerField(default=0),
        ),
    ]
