# Generated by Django 4.2.5 on 2023-10-26 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoupload', '0008_alter_point_is_share'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='file_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
