# Generated by Django 4.2.5 on 2023-10-27 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videoupload', '0010_video_thumbnail_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='file_url',
        ),
        migrations.RemoveField(
            model_name='video',
            name='thumbnail_url',
        ),
    ]
