# Generated by Django 4.2.5 on 2023-10-27 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoupload', '0011_remove_video_file_url_remove_video_thumbnail_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='file',
            field=models.FileField(max_length=255, upload_to='videos/'),
        ),
    ]
