# Generated by Django 4.2.5 on 2023-10-28 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoupload', '0013_alter_video_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='file_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='thumbnail_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
