# Generated by Django 4.2.5 on 2023-09-30 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relationship', '0002_rename_relationship_follow'),
    ]

    operations = [
        migrations.AddField(
            model_name='follow',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
    ]
