# Generated by Django 4.2.5 on 2023-09-30 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statusapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='statusapp',
            name='caption',
            field=models.TextField(default=''),
        ),
    ]
